### ISSUE TITLE
broken word-primitives on big endian platforms

### ISSUE THREAD

**Issue by hvr** [lpsmith/bytestring-builder#7]
The bug that affected `bytestring` sadly affects this package as well, see
https://github.com/haskell/bytestring/commit/4f52849a99753fab63d634769dd35a31f4d5a1b2 for more details

**Comment by lpsmith** [comment]
I will definitely update and release as soon as bytestring is released.   Any idea when that might happen?

**Comment by hvr** [comment]
@lpsmith https://hackage.haskell.org/package/bytestring-0.10.8.1 was just uploaded by @dcoutts!

**Comment by dcoutts** [comment]
Bah, @hvr beat me to commenting here. :-)

**Comment by lpsmith** [comment]
Ok, I updated to 0.10.8.1 and released to hackage: https://hackage.haskell.org/package/bytestring-builder-0.10.8.1.0  Thanks for the heads up!
