### ISSUE TITLE
Build failure due to "unrecognized option `--disable-benchmarks'" with v0.10.4.0 on GHC-7.0.4

### ISSUE THREAD

**Issue by sjakobi** [lpsmith/bytestring-builder#8]
See https://travis-ci.org/sjakobi/path/jobs/138399070#L589.

[The next build on GHC-7.0.4](https://travis-ci.org/sjakobi/path/jobs/138446120) succeeded because cabal chose v0.10.8.1.0 instead.

Could this be resolved by deprecating v0.10.4.0 and possibly other known-bad versions on hackage?

**Comment by lpsmith** [comment]
Ok, I went ahead and deprecated v0.10.4.0 and v0.10.4.0.1 on Hackage.    Let me know if you want anything more.

**Comment by sjakobi** [comment]
Thanks!
